Rewrite uniqueId strategies for manual sql queries.
FRINXio/resource-manager pull request #47
Opened 2022-04-20 11:07 UTC by Vasyl-9

Signed-off-by: Vasyl <vklevlanyk@frinx.io>

2022-04-21 08:56 UTC, marosmars requested changes

2022-04-21 08:56 UTC, marosmars commented on api-tests/src/bench/strategy.bench.js
> +            await testStrategy(strategyId, { ResourcePoolName: poolName }, poolName, strategyId, [], { desiredVlan: 85 }));
shouldn't this be pool id ?

2022-04-21 08:56 UTC, marosmars commented on api-tests/src/tests/unique_id.test.js
> +// test('unique_id pool capacity', async (t) => {
can this test be uncommented now that capacity is fixes also ?

2022-04-21 08:56 UTC, marosmars commented on api-tests/src/graphql-queries.js
> +                $poolId: ID!,
Should this be added here ? Is it necessary ? If not and this was caused due to modification of ResourcePoolInput in graphql schema then it needs to be changed

2022-04-21 08:56 UTC, marosmars commented on pools/allocatingpool.go
> +	manualSqlExecutionStrategies := [1]string{"unique_id"}
this should be a top level constant

2022-04-21 08:56 UTC, marosmars commented on pools/allocatingpool.go
> +func itemExists(arrayType interface{}, item interface{}) bool {
This implementation is a little strange, why not accept a slice of strings and ditch the reflection calls altogether ?

Also, why not use a hashMap as a set to check if the key is present instead (using a single line) ?

2022-04-21 08:56 UTC, marosmars commented on pools/allocatingpool.go
> +	if !itemExists(manualSqlExecutionStrategies, strat.Name) {
I would add comments explaining what this if means ... or better yet, encapsulate the condition of 
  !itemExists(manualSqlExecutionStrategies, strat.Name)
into a function called something like: needsFullListOfResources() .. so that the name explains what the if does

2022-04-21 08:58 UTC, marosmars commented on pools/allocating_strategies/strategies/src/unique_id_strategy.go
> +		if k != "pool_id" {
Is this if necessary ? Aren't we sending pool_id outside of pool properties now ?

2022-04-21 10:06 UTC, Vasyl-9 commented on api-tests/src/bench/strategy.bench.js
> +            await testStrategy(strategyId, { ResourcePoolName: poolName }, poolName, strategyId, [], { desiredVlan: 85 }));
Yes, it should be pool's identifier

2022-04-21 10:07 UTC, Vasyl-9 commented on api-tests/src/tests/unique_id.test.js
> +// test('unique_id pool capacity', async (t) => {
yes, sorry, me fault

2022-04-21 10:08 UTC, Vasyl-9 commented on api-tests/src/graphql-queries.js
> +                $poolId: ID!,
yes, we need to modify ResourcePoolInput so we need to add poolId to testStrategy input

2022-04-21 10:08 UTC, Vasyl-9 commented on pools/allocatingpool.go
> +	manualSqlExecutionStrategies := [1]string{"unique_id"}
done

2022-04-21 10:08 UTC, Vasyl-9 commented on pools/allocatingpool.go
> +func itemExists(arrayType interface{}, item interface{}) bool {
done

2022-04-21 10:08 UTC, Vasyl-9 commented on pools/allocatingpool.go
> +	if !itemExists(manualSqlExecutionStrategies, strat.Name) {
done

2022-04-21 10:09 UTC, Vasyl-9 commented on pools/allocating_strategies/strategies/src/unique_id_strategy.go
> +		if k != "pool_id" {
no, we don't need it. Done

2022-04-22 09:16 UTC, marosmars approved these changes

2022-04-22 09:16 UTC, merged