handle value conversion
FRINXio/resource-manager pull request #93
Opened 2023-03-31 15:09 UTC by MarcoMruz

2023-03-31 18:57 UTC, Vasyl-9 requested changes

2023-03-31 18:57 UTC, Vasyl-9 commented on pools/allocating_strategies/strategies/src/ipv4_prefix_strategy.go
> +	fmt.Println("eskere", desiredSizeErr, desiredSize, isSubnet)
unnecessary comment

2023-04-01 10:42 UTC, MarcoMruz commented on pools/allocating_strategies/strategies/src/ipv4_prefix_strategy.go
> +		desiredSize, desiredSizeErr = NumberToInt(value)
the addition of 2 is still there but lower in the code... I added security guards that will return the function as soon as possible when there was an error so that server is not returning internal server error

2023-04-01 10:42 UTC, MarcoMruz commented on pools/allocating_strategies/strategies/src/ipv4_prefix_strategy.go
> +		desiredSize, desiredSizeErr = NumberToInt(value)
https://github.com/FRINXio/resource-manager/blob/fix-value-conversion/pools/allocating_strategies/strategies/src/ipv4_prefix_strategy.go#L242

2023-04-01 16:23 UTC, closed without merging